apiVersion: v1
kind: Service
metadata:
  name: {{ include "ginchat.fullname" . }}
  labels:
    {{- include "ginchat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: api
  selector:
    {{- include "ginchat.selectorLabels" . | nindent 4 }}
