definitions:
  device.DiskStatus:
    properties:
      all:
        type: integer
      free:
        type: integer
      used:
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/api/v1/host/disk:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: capacity of disk
          schema:
            $ref: '#/definitions/device.DiskStatus'
      security:
      - ApiKeyAuth: []
      summary: get disk status
      tags:
      - host
swagger: "2.0"
